CREATE TABLE "ATG_3021_BI_RPTS_SET"(
 "RPT_ID" CHAR(6) CASE ,
 "EMAIL1" VARCHAR(150) CASE ,
 "EMAIL2" VARCHAR(150) CASE ,
 "EMAIL3" VARCHAR(150) CASE ,
 "EMAIL4" VARCHAR(150) CASE ,
 "EMAIL5" VARCHAR(150) CASE ,
 "EMAIL" INTEGER,
 "PRINT" INTEGER,
 "COPIES" INTEGER DEFAULT '1',
 "PRINTER" VARCHAR(100) CASE ,
 "SUBJECT" VARCHAR(150) CASE ,
 "DEFAULT_FROM" VARCHAR(150));